# Generated by Django 4.2.7 on 2023-11-26 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_archiveattendance_user_temporaryattendance_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiveattendance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='temporaryattendance',
            name='user',
        ),
    ]
