# Generated by Django 4.2.7 on 2023-11-27 23:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_archiveattendance_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchiveAttendance',
        ),
        migrations.AddField(
            model_name='temporaryattendance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
