# Generated by Django 4.2.7 on 2023-12-11 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_archiveattendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('timein_names', models.CharField(max_length=100)),
                ('timeout_names', models.CharField(max_length=100)),
                ('breakout_names', models.CharField(max_length=100)),
                ('breakin_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'archive',
            },
        ),
        migrations.RemoveField(
            model_name='temporaryattendance',
            name='timeout_updated',
        ),
    ]
