# Generated by Django 4.2.7 on 2023-12-11 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_archive_remove_temporaryattendance_timeout_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='breakin_name',
            new_name='breakin_names',
        ),
    ]
