# Generated by Django 4.2.7 on 2023-12-11 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_breakin_name_archive_breakin_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='afternoonBreakout_timestamps',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='archive',
            name='afternoonTimeout_timestramps',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='archive',
            name='breakin_timestamps',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='archive',
            name='breakout_timestamps',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='archive',
            name='timein_timestamps',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='archive',
            name='timeout_timestamps',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
