# Generated by Django 4.2.7 on 2023-12-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_archive_afternoonbreakout_timestamps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='afternoonBreakout_timestamps',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='afternoonTimeout_timestramps',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='breakin_timestamps',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='breakout_timestamps',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='timein_timestamps',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='timeout_timestamps',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
