# Generated by Django 4.2.7 on 2023-12-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_archive_afternoonbreakout_timestamps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='breakout_names',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
