# Generated by Django 4.2.7 on 2023-12-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_archive_breakout_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryattendance',
            name='breakout_timer',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
