# Generated by Django 4.2.7 on 2023-12-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_temporaryattendance_breakout_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='breakin_names',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='timein_names',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='timeout_names',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
