# Generated by Django 4.2.7 on 2023-12-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_archive_breakin_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryattendance',
            name='breakout_timer',
        ),
        migrations.AddField(
            model_name='temporaryattendance',
            name='timeout_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
