# Generated by Django 4.2.7 on 2023-12-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_temporaryattendance_breakout_timer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryattendance',
            name='timeout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
