# Generated by Django 4.2.7 on 2023-12-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_temporaryattendance_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryattendance',
            name='timeout',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
