# Generated by Django 4.2.7 on 2023-12-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_temporaryattendance_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryattendance',
            name='breakin_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporaryattendance',
            name='breakout_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
