# Generated by Django 4.2.7 on 2023-12-19 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_temporaryattendance_breakin_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryattendance',
            name='breakin_updated',
        ),
        migrations.RemoveField(
            model_name='temporaryattendance',
            name='breakout_updated',
        ),
        migrations.RemoveField(
            model_name='temporaryattendance',
            name='timeout_updated',
        ),
    ]
