# Generated by Django 4.2.7 on 2023-12-21 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_temporaryattendance_branch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryattendance',
            name='branch_name',
        ),
    ]
