# Generated by Django 4.2.7 on 2023-12-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_temporaryattendance_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryattendance',
            name='branch_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
