# Generated by Django 4.2.7 on 2023-12-27 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_temporaryattendance_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryattendance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
