# Generated by Django 4.2.7 on 2023-12-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_temporaryattendance_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
            ],
            options={
                'db_table': 'qr_list',
            },
        ),
    ]
