# Generated by Django 4.2.7 on 2024-01-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_qrlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='qr_existing_list',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('employee_unique_id', models.CharField(max_length=200)),
                ('fn', models.CharField(max_length=100)),
                ('mn', models.CharField(max_length=100)),
                ('ln', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=200)),
                ('qr_code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'qr_existing_list',
            },
        ),

    ]
