# Generated by Django 4.2.7 on 2024-01-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_qr_existing_list_alter_qrlist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qr_existing_list',
            old_name='qr_code',
            new_name='qr_codes',
        ),
        migrations.AlterField(
            model_name='qrlist',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
