# Generated by Django 4.2.7 on 2024-01-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_rename_qr_code_qr_existing_list_qr_codes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_dbf_to_sql',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('bank', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'md_dbf_to_sql',
            },
        ),
    ]
